---
- name: EIP HA
  when:
    - vrrp_interface is defined
    - vrrp_vip is defined
  become: true
  block:
    - name: install sdnagent rpm
      package:
        name: yunion-sdnagent
        state: latest
      when:
      - is_centos_x86 is defined
      notify: restart eipgw

    - name: get vars
      shell: |
        /opt/yunion/bin/fetch-rcadmin.sh | sed \
        -e 's#export ##' \
        -e 's#OS_REGION_NAME#oc_region#' \
        -e 's#OS_AUTH_URL#oc_auth_url#' \
        -e 's#OS_USERNAME#oc_admin_user#' \
        -e 's#OS_PASSWORD#oc_admin_password#' \
        -e 's#OS_PROJECT_NAME#oc_admin_project#' \
        -e 's#=#: "#' \
        -e 's#$#"#' | \
        grep '^oc_'
      register: oc_vars
      delegate_to: "{{ k8s_controlplane_host }}"

    - name: write oc vars
      copy:
        content: "{{ oc_vars.stdout }}"
        dest: /tmp/oc_vars

    - name: get oc vars
      run_once: yes
      fetch:
        src: /tmp/oc_vars
        dest: /tmp/oc_vars
        flat: yes

    - name: load vars
      run_once: yes
      include_vars: /tmp/oc_vars

    - name: clean tmp files
      file:
        path: /tmp/oc_vars
        state: absent

    - name: enable ip forwarding
      sysctl:
        name: net.ipv4.ip_forward
        value: '1'
        sysctl_set: yes
        state: present
        reload: yes

    - name: make sdnagent.conf
      template:
        src: sdnagent.conf.j2
        dest: /etc/yunion/sdnagent.conf
      notify: restart eipgw

    - name: install keepalived
      package:
        name: keepalived
        state: present

    - name: mkdir /etc/keepalived
      file:
        name: /etc/keepalived
        state: directory
        owner: root
        group: root

    - name: make keepalived eipgw.conf
      template:
        src: keepalived-eipgw.conf.j2
        dest: /etc/keepalived/eipgw.conf
      vars:
        vrrp_notify_script: /etc/keepalived/eipgw-notify.sh
      notify: restart eipgw

    - name: copy keepalived notify script
      copy:
        src: keepalived-eipgw-notify.sh
        dest: /etc/keepalived/eipgw-notify.sh
        owner: root
        group: root
        mode: 0700

    - name: enable yunion-sdnagent-eipgw service
      service:
        name: yunion-sdnagent-eipgw
        state: started
        enabled: yes
