  # from centos 7.9 2009 to centos stream 8
- name: Assert {{ ansible_distribution }} {{ ansible_distribution_version }} conditions
  fail:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} is not supported~"
  when:
    - ansible_distribution_version is version('7.9', '<') or ansible_distribution_version is version('8', '>')