---

- name: set var for {{ onecloud_version }}
  set_fact:
    is_supported: false

- name: Set distribution version facts
  set_fact:
    ansible_distribution_version: "{{ ansible_distribution_version }}"
    ansible_distribution_release: "{{ ansible_distribution_release }}"

- name: Assert {{ ansible_distribution }} {{ ansible_distribution_version }} conditions
  set_fact:
    is_supported: true
  when:
    - ansible_distribution_version is version('3.1', '>=')
    - ansible_distribution_version is version('4', '<')
    - ansible_distribution == 'TencentOS'
    - ansible_architecture == 'x86_64'
    - onecloud_version is defined
    - onecloud_version is version('v3.9', '>=')
    - onecloud_version is version('v3.11', '<=')

- name: Evaluate {{ ansible_distribution }} {{ ansible_distribution_version }} conditions
  fail:
    msg: "{{ ansible_distribution }} {{ ansible_distribution_version }} {{ ansible_distribution_release }} is not supported by {{ onecloud_version }}"
  when:
  - is_supported | default(true) | bool == false

