- name: "Add cloud rpm repository {{ yunion_yum_repo }}"
  copy:
    content: |
      [yunion-repo-offline]
      name=Packages for Yunion Multi-Cloud Platform -
      baseurl=https://iso.yunion.cn/centos/$releasever/{{onecloud_version_abbr}}/$basearch
      sslverify=0
      failovermethod=priority
      enabled=1
      gpgcheck=0
    dest: /etc/yum.repos.d/yunion.repo
  become: yes
  retries: 3
  delay: 30
  when:
  - offline_data_path is not defined or offline_data_path | length == 0

- name: Include RedHat Family Common Tasks
  include_tasks: redhat.yml

- name: install misc obsolete packages
  package:
    name: "{{ package_item }}"
    disablerepo: "{{ (online_status != 'online') | ternary('*', omit) }}"
    enablerepo: "{{ (online_status != 'online') | ternary('yunion-*', omit) }}"
  become: yes
  loop_control:
    index_var: item_index
    loop_var: package_item
  with_items:
  - yunion-qemu-2.12.1
  when:
  - is_centos_x86 is defined
  tags:
  - package
  register: obsolete_packages
  until: obsolete_packages.rc == 0
  retries: 3
  delay: 30


