- name: Create directory for ocnet cni conf
  file:
    path: /etc/yunion/cni/net.d
    state: directory
    mode: '0755'

- name: Copy yunion-containerd config file
  ansible.builtin.copy:
    content: "{{ lookup('file', 'config.toml') }}"
    dest: /root/yunion/containerd/config.toml
    mode: '0644'
  notify: enable yunion-containerd

- name: Copy yunion-containerd.service file
  ansible.builtin.copy:
    content: "{{ lookup('file', 'yunion-containerd.service') }}"
    dest: /usr/lib/systemd/system/yunion-containerd.service
    mode: '0644'
  notify: enable yunion-containerd

- name: Enable and start yunion-containerd service
  ansible.builtin.systemd:
    name: yunion-containerd
    enabled: yes
    state: started

- name: Copy ocnet-cni.conflist file
  ansible.builtin.copy:
    content: "{{ lookup('file', '10-ocnet-cni.conflist') }}"
    dest: /etc/yunion/cni/net.d/10-ocnet-cni.conflist
    mode: '0644'
  notify: restart yunion-containerd

- name: Check crictl version
  shell: |
    crictl -r unix:///var/run/onecloud/containerd/containerd.sock version
    crictl -r unix:///var/run/onecloud/containerd/containerd.sock pods
  register: crictl_version
  changed_when: false

- debug: var=crictl_version.stdout_lines
