- name: remove sync-user option
  shell: |
    tmp=$(mktemp).yaml
    {{ K3S_CMDLINE_PREFIX }} kubectl get deployment onecloud-operator -n onecloud -o yaml > $tmp
    sed -i '/sync-user$/d' $tmp
    kubectl replace -f $tmp
    rm -f $tmp
  args:
    executable: /bin/bash
