---
- name: Ensure a job that runs daily
  cron:
    name: "Remove unused dangling k3s container images"
    special_time: daily
    user: root
    job: "k3s crictl rmi --prune"
    cron_file: yunion_k3s_image_prune
  become: true

- name: ensure /opt/yunion/scripts path exists
  file:
    path: /opt/yunion/scripts
    state: directory
  become: true

- name: enable auto backup
  include_role:
    name: utils/auto-backup-services
  when:
  - offline_data_path | length > 0
