---
- name: Ensure a job that runs daily
  include_tasks: "{{ k8s_or_k3s }}_image_prune.yml"

- name: ensure /opt/yunion/scripts path exists
  file:
    path: /opt/yunion/scripts
    state: directory
  become: true

- name: enable auto backup
  include_role:
    name: utils/auto-backup-services
  when:
  - offline_data_path | length > 0
