- name: test var enable_eip_man
  environment:
    KUBECONFIG: /etc/kubernetes/admin.conf
  shell: |
    source <(/opt/yunion/bin/fetch-rcadmin.sh cluster rcadmin)
    if grep -q '^sdn_enable_eip_man:' /etc/yunion/host.conf; then
      sed -i -e 's#^sdn_enable_eip_man.*#sdn_enable_eip_man: true#' /etc/yunion/host.conf
    else
      echo 'sdn_enable_eip_man: true' >> /etc/yunion/host.conf
    fi
    kubectl rollout restart ds -n onecloud default-host
  args:
    executable: /bin/bash
  become: yes
  ignore_errors: yes
  changed_when: false
  failed_when: false
  when:
  - enable_eip_man | default(false) | bool == true
  - product_version | default('fullstack') | lower in ['fullstack', 'edge']

